# Generated by Django 3.1.5 on 2021-01-10 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the                             format: '9876543210'. Up to 10 digits allowed.", regex='^[6-9]\\d{9}$')]),
        ),
    ]
